# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Plugins/CheckerPlugins/CodeStyleChecker/CodeStyleCheckerDialog.ui'
#
# Created: Tue Nov 18 17:53:57 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CodeStyleCheckerDialog(object):
    def setupUi(self, CodeStyleCheckerDialog):
        CodeStyleCheckerDialog.setObjectName("CodeStyleCheckerDialog")
        CodeStyleCheckerDialog.resize(650, 700)
        CodeStyleCheckerDialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CodeStyleCheckerDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filterFrame = QtWidgets.QFrame(CodeStyleCheckerDialog)
        self.filterFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filterFrame.setObjectName("filterFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.filterFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.filterFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.excludeFilesEdit = E5ClearableLineEdit(self.filterFrame)
        self.excludeFilesEdit.setObjectName("excludeFilesEdit")
        self.gridLayout.addWidget(self.excludeFilesEdit, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.filterFrame)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 9, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.filterFrame)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.fixButton = QtWidgets.QPushButton(self.filterFrame)
        self.fixButton.setObjectName("fixButton")
        self.verticalLayout.addWidget(self.fixButton)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.loadDefaultButton = QtWidgets.QPushButton(self.filterFrame)
        self.loadDefaultButton.setObjectName("loadDefaultButton")
        self.verticalLayout.addWidget(self.loadDefaultButton)
        self.storeDefaultButton = QtWidgets.QPushButton(self.filterFrame)
        self.storeDefaultButton.setObjectName("storeDefaultButton")
        self.verticalLayout.addWidget(self.storeDefaultButton)
        self.resetDefaultButton = QtWidgets.QPushButton(self.filterFrame)
        self.resetDefaultButton.setObjectName("resetDefaultButton")
        self.verticalLayout.addWidget(self.resetDefaultButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 4, 9, 1)
        self.label = QtWidgets.QLabel(self.filterFrame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.excludeMessagesEdit = E5ClearableLineEdit(self.filterFrame)
        self.excludeMessagesEdit.setObjectName("excludeMessagesEdit")
        self.gridLayout.addWidget(self.excludeMessagesEdit, 1, 1, 1, 1)
        self.excludeMessagesSelectButton = QtWidgets.QToolButton(self.filterFrame)
        self.excludeMessagesSelectButton.setObjectName("excludeMessagesSelectButton")
        self.gridLayout.addWidget(self.excludeMessagesSelectButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.filterFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.includeMessagesEdit = E5ClearableLineEdit(self.filterFrame)
        self.includeMessagesEdit.setObjectName("includeMessagesEdit")
        self.gridLayout.addWidget(self.includeMessagesEdit, 2, 1, 1, 1)
        self.includeMessagesSelectButton = QtWidgets.QToolButton(self.filterFrame)
        self.includeMessagesSelectButton.setObjectName("includeMessagesSelectButton")
        self.gridLayout.addWidget(self.includeMessagesSelectButton, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.filterFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.fixIssuesEdit = E5ClearableLineEdit(self.filterFrame)
        self.fixIssuesEdit.setObjectName("fixIssuesEdit")
        self.gridLayout.addWidget(self.fixIssuesEdit, 3, 1, 1, 1)
        self.fixIssuesSelectButton = QtWidgets.QToolButton(self.filterFrame)
        self.fixIssuesSelectButton.setObjectName("fixIssuesSelectButton")
        self.gridLayout.addWidget(self.fixIssuesSelectButton, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.filterFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.noFixIssuesEdit = E5ClearableLineEdit(self.filterFrame)
        self.noFixIssuesEdit.setObjectName("noFixIssuesEdit")
        self.gridLayout.addWidget(self.noFixIssuesEdit, 4, 1, 1, 1)
        self.noFixIssuesSelectButton = QtWidgets.QToolButton(self.filterFrame)
        self.noFixIssuesSelectButton.setObjectName("noFixIssuesSelectButton")
        self.gridLayout.addWidget(self.noFixIssuesSelectButton, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.filterFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineLengthSpinBox = QtWidgets.QSpinBox(self.filterFrame)
        self.lineLengthSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineLengthSpinBox.setMinimum(60)
        self.lineLengthSpinBox.setMaximum(119)
        self.lineLengthSpinBox.setProperty("value", 79)
        self.lineLengthSpinBox.setObjectName("lineLengthSpinBox")
        self.horizontalLayout_3.addWidget(self.lineLengthSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.filterFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.docTypeComboBox = QtWidgets.QComboBox(self.filterFrame)
        self.docTypeComboBox.setObjectName("docTypeComboBox")
        self.horizontalLayout_4.addWidget(self.docTypeComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 1, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hangClosingCheckBox = QtWidgets.QCheckBox(self.filterFrame)
        self.hangClosingCheckBox.setObjectName("hangClosingCheckBox")
        self.horizontalLayout_2.addWidget(self.hangClosingCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repeatCheckBox = QtWidgets.QCheckBox(self.filterFrame)
        self.repeatCheckBox.setObjectName("repeatCheckBox")
        self.horizontalLayout.addWidget(self.repeatCheckBox)
        self.fixIssuesCheckBox = QtWidgets.QCheckBox(self.filterFrame)
        self.fixIssuesCheckBox.setEnabled(False)
        self.fixIssuesCheckBox.setObjectName("fixIssuesCheckBox")
        self.horizontalLayout.addWidget(self.fixIssuesCheckBox)
        self.ignoredCheckBox = QtWidgets.QCheckBox(self.filterFrame)
        self.ignoredCheckBox.setEnabled(False)
        self.ignoredCheckBox.setObjectName("ignoredCheckBox")
        self.horizontalLayout.addWidget(self.ignoredCheckBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.filterFrame)
        self.resultList = QtWidgets.QTreeWidget(CodeStyleCheckerDialog)
        self.resultList.setAlternatingRowColors(True)
        self.resultList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.resultList.setObjectName("resultList")
        self.verticalLayout_2.addWidget(self.resultList)
        self.checkProgressLabel = E5SqueezeLabelPath(CodeStyleCheckerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkProgressLabel.sizePolicy().hasHeightForWidth())
        self.checkProgressLabel.setSizePolicy(sizePolicy)
        self.checkProgressLabel.setText("")
        self.checkProgressLabel.setObjectName("checkProgressLabel")
        self.verticalLayout_2.addWidget(self.checkProgressLabel)
        self.checkProgress = QtWidgets.QProgressBar(CodeStyleCheckerDialog)
        self.checkProgress.setProperty("value", 0)
        self.checkProgress.setOrientation(QtCore.Qt.Horizontal)
        self.checkProgress.setObjectName("checkProgress")
        self.verticalLayout_2.addWidget(self.checkProgress)
        self.buttonBox = QtWidgets.QDialogButtonBox(CodeStyleCheckerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CodeStyleCheckerDialog)
        self.repeatCheckBox.toggled['bool'].connect(self.fixIssuesCheckBox.setEnabled)
        self.repeatCheckBox.toggled['bool'].connect(self.ignoredCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CodeStyleCheckerDialog)
        CodeStyleCheckerDialog.setTabOrder(self.startButton, self.loadDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.loadDefaultButton, self.excludeFilesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.excludeFilesEdit, self.excludeMessagesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.excludeMessagesEdit, self.excludeMessagesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.excludeMessagesSelectButton, self.includeMessagesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.includeMessagesEdit, self.includeMessagesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.includeMessagesSelectButton, self.fixIssuesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesEdit, self.fixIssuesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesSelectButton, self.noFixIssuesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.noFixIssuesEdit, self.noFixIssuesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.noFixIssuesSelectButton, self.lineLengthSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineLengthSpinBox, self.docTypeComboBox)
        CodeStyleCheckerDialog.setTabOrder(self.docTypeComboBox, self.hangClosingCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.hangClosingCheckBox, self.repeatCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.repeatCheckBox, self.fixIssuesCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesCheckBox, self.ignoredCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.ignoredCheckBox, self.resultList)
        CodeStyleCheckerDialog.setTabOrder(self.resultList, self.fixButton)
        CodeStyleCheckerDialog.setTabOrder(self.fixButton, self.storeDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.storeDefaultButton, self.resetDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.resetDefaultButton, self.buttonBox)

    def retranslateUi(self, CodeStyleCheckerDialog):
        _translate = QtCore.QCoreApplication.translate
        CodeStyleCheckerDialog.setWindowTitle(_translate("CodeStyleCheckerDialog", "Code Style Check Result"))
        CodeStyleCheckerDialog.setWhatsThis(_translate("CodeStyleCheckerDialog", "<b>Code Style Check Results</b>\n"
"<p>This dialog shows the results of the code style check. Double clicking an\n"
"entry will open an editor window and position the cursor at the respective line and position.</p>"))
        self.label_2.setText(_translate("CodeStyleCheckerDialog", "Exclude Files:"))
        self.excludeFilesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter filename patterns of files to be excluded separated by a comma"))
        self.startButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to start the code style check run"))
        self.startButton.setText(_translate("CodeStyleCheckerDialog", "Start"))
        self.fixButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to fix the selected issues"))
        self.fixButton.setText(_translate("CodeStyleCheckerDialog", "Fix Selected"))
        self.loadDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to load the default values"))
        self.loadDefaultButton.setText(_translate("CodeStyleCheckerDialog", "Load Defaults"))
        self.storeDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to store the current values as defaults"))
        self.storeDefaultButton.setText(_translate("CodeStyleCheckerDialog", "Store Defaults"))
        self.resetDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to reset the default values"))
        self.resetDefaultButton.setText(_translate("CodeStyleCheckerDialog", "Reset Defaults"))
        self.label.setText(_translate("CodeStyleCheckerDialog", "Exclude Messages:"))
        self.excludeMessagesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes or categories to be excluded separated by a comma"))
        self.excludeMessagesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_3.setText(_translate("CodeStyleCheckerDialog", "Included Messages:"))
        self.includeMessagesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes or categories to be included separated by a comma"))
        self.includeMessagesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_4.setText(_translate("CodeStyleCheckerDialog", "Fix Issues:"))
        self.fixIssuesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes of issues to be fixed automatically (leave empty to fix all)"))
        self.fixIssuesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_6.setText(_translate("CodeStyleCheckerDialog", "Don\'t Fix Issues:"))
        self.noFixIssuesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes of issues not to be fixed automatically"))
        self.noFixIssuesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_5.setText(_translate("CodeStyleCheckerDialog", "Max. Line Length:"))
        self.lineLengthSpinBox.setStatusTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed line length (PEP-8: 79 characters)"))
        self.label_7.setText(_translate("CodeStyleCheckerDialog", "Docstring Type:"))
        self.docTypeComboBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select the rule set for docstrings"))
        self.hangClosingCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to allow hanging closing brackets"))
        self.hangClosingCheckBox.setText(_translate("CodeStyleCheckerDialog", "Allow hanging closing brackets"))
        self.repeatCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to repeat each message type"))
        self.repeatCheckBox.setText(_translate("CodeStyleCheckerDialog", "Repeat messages"))
        self.fixIssuesCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to fix some issues"))
        self.fixIssuesCheckBox.setText(_translate("CodeStyleCheckerDialog", "Fix issues automatically"))
        self.ignoredCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to show ignored issues"))
        self.ignoredCheckBox.setText(_translate("CodeStyleCheckerDialog", "Show ignored"))
        self.resultList.setWhatsThis(_translate("CodeStyleCheckerDialog", "<b>Result List</b>\n"
"<p>This list shows the results of the code style check. Double clicking\n"
"an entry will open this entry in an editor window and position the cursor at\n"
"the respective line and position.</p>"))
        self.resultList.setSortingEnabled(True)
        self.resultList.headerItem().setText(0, _translate("CodeStyleCheckerDialog", "File/Line"))
        self.resultList.headerItem().setText(1, _translate("CodeStyleCheckerDialog", "Code"))
        self.resultList.headerItem().setText(2, _translate("CodeStyleCheckerDialog", "Message"))
        self.checkProgress.setToolTip(_translate("CodeStyleCheckerDialog", "Shows the progress of the code style check"))
        self.checkProgress.setFormat(_translate("CodeStyleCheckerDialog", "%v/%m Files"))

from E5Gui.E5LineEdit import E5ClearableLineEdit
from E5Gui.E5SqueezeLabels import E5SqueezeLabelPath
